/** @type {import('tailwindcss').Config} */
// Design tokens ported from the Stitch export so the same class names
// (bg-surface-dark, text-primary, font-headline-md, p-gutter, …) work here.
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "background-dark": "#0F1117",
        "background-light": "#F8FAFC",
        surface: "#12131a",
        "surface-dark": "#171A23",
        "surface-dim": "#12131a",
        "surface-bright": "#383940",
        "surface-variant": "#33343c",
        "surface-container-lowest": "#0d0e15",
        "surface-container-low": "#1a1b22",
        "surface-container": "#1e1f26",
        "surface-container-high": "#282a31",
        "surface-container-highest": "#33343c",
        "border-dark": "#262B38",
        "border-light": "#E2E8F0",
        outline: "#8e909f",
        "outline-variant": "#444653",
        primary: "#b7c4ff",
        "primary-container": "#6e8bff",
        "on-primary-container": "#002179",
        "accent-light": "#4F46E5",
        "inverse-primary": "#3554c6",
        secondary: "#42e1b3",
        "secondary-container": "#00c599",
        "surface-tint": "#b7c4ff",
        tertiary: "#ffb960",
        "tertiary-container": "#cd8200",
        "error-coral": "#FF6B7D",
        "on-surface": "#e2e1eb",
        "on-surface-variant": "#c4c5d6",
        "text-primary-dark": "#E6E9F0",
        "text-muted-dark": "#8A92A6",
        "text-muted-light": "#64748B",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: { xs: "4px", sm: "12px", base: "8px", md: "16px", lg: "24px", gutter: "24px", xl: "32px", margin: "32px" },
      fontFamily: {
        "display-lg": ["Sora", "sans-serif"],
        "headline-lg": ["Sora", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "body-lg": ["'IBM Plex Sans'", "sans-serif"],
        "body-md": ["'IBM Plex Sans'", "sans-serif"],
        "body-sm": ["'IBM Plex Sans'", "sans-serif"],
        "mono-metrics": ["'IBM Plex Mono'", "monospace"],
        "label-caps": ["'IBM Plex Mono'", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "mono-metrics": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
